"""recommendation impression

Revision ID: 002_recommendation_impression
Revises: 001_initial_schema
Create Date: 2026-09-28 18:22:05.941887
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '002_recommendation_impression'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_impression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('recommended_at', sa.DateTime(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=True),
    sa.Column('recommender', sa.String(length=30), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('policy_version', sa.String(length=30), nullable=False),
    sa.Column('selection_probability', sa.Float(), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('decision_context', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['user_quest.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    op.create_index('ix_recommendation_impression_user_shown', 'recommendation_impression', ['user_id', 'shown_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendation_impression_user_shown', table_name='recommendation_impression')
    op.drop_table('recommendation_impression')
    # ### end Alembic commands ###
